CREATE TABLE employees (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    isActive INTEGER NOT NULL DEFAULT 1,
    isAdmin INTEGER NOT NULL DEFAULT 0
);